### PR TITLE
Implemented Contact form in Contact Section

### LINKED ISSUE #1: Implement Contact form in Contact Section
Hey, I want to add a contact form in the contact section, which sends mail to my mail address which is - itsamanyadav18@gmail.com

### PR DESCRIPTION
**Pull request by aadil080**
**In this pull request I have made the following changes**
*Fixed issue* #1

**Implemented Contact form in contact section for communication with the developer.**

### CODE REVIEW

**Comment by aadil080** [comment]
Hi Aman, I have submitted a pull request for the issue. Could you please review it and provide your feedback? I would appreciate any changes or suggestions you may have. Thank you!

**Comment by Its-Aman-Yadav** [comment]
Hey @aadil080, the part of code that you uncommented is not working properly, could you please make it working?

**Comment by aadil080** [comment]
Hey @Its-Aman-Yadav , now can you please check the code. I have made some changes so user can seemlessly contact with you using the contact form. If it requires any more further changes you can call out to me.

**Comment by Its-Aman-Yadav** [comment]
@aadil080 Still there are some problems with the form -
1 -  There are two submit buttons are there
2 - Submit button is not working 

Please make it work and remove that extra button 
Thanks

**Comment by aadil080** [comment]
Hey @Its-Aman-Yadav, can you please provide the **screenshot** about the inconvenience.

**Comment by Its-Aman-Yadav** [comment]
image

**Comment by Its-Aman-Yadav** [comment]
There is two submit button, please remove one

**Comment by aadil080** [comment]
Hey @Its-Aman-Yadav , Sorry for inconvenience I have forgot about the merge of both branches. Now the conflict have been resolved. So, kindly check the code if it is working or not.
Thank you
Screenshot from 2023-06-20 18-11-23

**Comment by Its-Aman-Yadav** [comment]
Okay, one problem is sorted but still, the submit button is not working....
The Submit button should send the mail to the desired mail address after submitting the form

**Comment by aadil080** [comment]
Hii @Its-Aman-Yadav , the submit button will work if the user have installed an email client. As I am using ubuntu I am able to send message. There is a tool called as [EmailJS](https://www.emailjs.com/) here you can create an account and by manipulate some code in javascript, the user can send message directly from the code.
Thank you.
Screenshot from 2023-06-20 21-15-03

**Comment by Its-Aman-Yadav** [comment]
Great Share, but I am unable to integrate EmailJS in my code, could you please elaborate?

**Comment by aadil080** [comment]
@Its-Aman-Yadav I don't have much knowledge about [EmailJS](https://www.emailjs.com/) but it is quite easy to use it. You can refer to their official [Docs](https://www.emailjs.com/docs/) for any query.
Now you can close the PR.

**Comment by Its-Aman-Yadav** [comment]
Thanks @aadil080 for your contribution

**Pull request merged**
